README.en.md
README.md

update video link in READMEs

---

launch/object_tracking.launch.py

カメラサンプルでmouseとobject_trackingノードの起動にマルチスレッドを使用します。
これまではシングルスレッドを使っていたため動作が安定しない（動作がフリーズする）ことがありました。
参考：
- https://github.com/ros2/rclcpp/blob/master/rclcpp_components/src/component_container.cpp
- https://github.com/ros2/rclcpp/blob/master/rclcpp_components/src/component_container_mt.cpp
いいえ。
実機で動作確認しました。

Use multi threads in the object tracking example to stabilize the tracking

---

README.en.md
README.md

Update Gamepad F710 usage in README

---

raspimouse_ros2_examples/joystick_control.py

ジョイコントロールサンプルでLEDを点灯します。
ROS1サンプル集では実装済みの機能です。
いいえ。
ラズパイマウスの実機で動作確認しました。

Turn on/off leds with joy inputs

---

README.en.md
README.md
config/default.rviz
config/mapper_params_offline.yaml
config/mapper_params_online_async.yaml
launch/mouse_with_lidar.launch.py
launch/slam.launch.py
package.xml

LiDARとslam_toolboxを使用したサンプルを追加します。
使用したLiDAR
- LDS-01

Add lidar example

---

README.en.md
README.md

#16  の対応です。画像の参照元をrt-net.github.io/images に変更します。

Port images from the images branch to rt-net.github.io/images

---

.ci.rosinstall
CMakeLists.txt
README.en.md
README.md
include/raspimouse_ros2_examples/direction_controller_component.hpp
launch/direction_controller.launch.py
src/direction_controller.cpp
src/direction_controller_component.cpp

9軸IMUセンサモジュールを使うサンプルを追加しました。
ROS1 サンプル集とほぼ同じ動作です。
https://github.com/rt-net/raspimouse_ros_examples#direction_control
RasPi4 & Ubuntu 18.04 で動作確認しました。
9軸IMUセンサのROS 2パッケージはdashin-develブランチを使用してます。
https://github.com/rt-net/rt_usb_9axisimu_driver

Add direction control example

---

.ci.rosinstall
.github/workflows/industrial_ci.yml
README.en.md
README.md

`raspimouse2`と`rt_usb_9axisimu_driver`の`dashing`パッケージがリリースされたので、
インストール手順を更新します。
また、industrial_ciでの、`.ci.rosintall`によるインストールも廃止します。
このPR後、`raspimouse_ros2_examples`の`dashing-devel`ブランチを作成します。
いいえ
CIで、パッケージをインストールできるかを確認します。

Install raspimouse2 and imu packages via rosdep command

---

package.xml

slam_toolboxがpackage.xmlに追加されていなかったため
直接クローズはしませんが、#24 が関連します
Ubuntu 18.04 にて、rosdepコマンドでパッケージがインストールされることを確認しています。

Add slam_toolbox to package.xml

---

.github/workflows/industrial_ci.yml
src/direction_controller_component.cpp
src/lifecycle_node_manager.cpp
src/line_follower_component.cpp
src/object_tracking_component.cpp

ROS 2 Foxy 対応に向けてCIを更新します。
また、CIのLintチェックを通すため、ソースコードを修正します。
ソースコードは`ament_uncrustify --reformat`コマンドで自動修正しています。
いいえ
CIが通ることを確認しています。
実機テストはしていません。
ROS 2 Foxyでの実機テストに伴う修正は別PRで行います。
（Dashingにもマージすべき修正点があるため）

Update CI to support ROS Foxy

---

launch/teleop_joy.launch.py
package.xml

- ROS 2 foxy向けの修正です。
- joystick_controlサンプルで、`joy`パッケージではなく`joy_linux`パッケージを使用します。
- `joy`パッケージのREADMEに、`/dev/input/js*`にアクセスする場合は`joy_linux`を使用すると記載されています。
- https://github.com/ros-drivers/joystick_drivers/tree/ros2/joy#technical-note-about-interfacing-with-the-joystick-on-linux
- ROS 2 Dashingではjoy_linuxパッケージがリリースされていないため、`dashing-devel`との互換性がなくなります。
いいえ
ROS 2 Foxy (RasPi 4、PC)にて、下記コマンドが実行できることを確認しています。
```sh
$ ros2 launch raspimouse_ros2_examples teleop_joy.launch.py joydev:="/dev/input/js0" joyconfig:=dualshock3 mouse:=true
$ ros2 launch raspimouse_ros2_examples teleop_joy.launch.py joydev:="/dev/input/js1" joyconfig:=f710 mouse:=true
$ ros2 run raspimouse raspimouse
$ ros2 launch raspimouse_ros2_examples teleop_joy.launch.py mouse:=false joyconfig:=dualshock3
```

Use joy_linux instead of joy

---

README.en.md
README.md

SLAMサンプルの説明に`use_pulse_counters`パラメータの設定方法を追記します。
この変更は、`dashing-devel`、`foxy-devel`の両方に反映する予定です。
いいえ
ドキュメント変更のためテストなしです。
いいえ

Add descriptions to READMEs for use_pulse_counters param settings

---

config/default.rviz

- Foxy（`foxy-devel`）向けの変更です
- LiDARの`/scan`トピックとslam_toolboxの`/graph_visualization`トピックをRVizに表示させるため、コンフィグファイルを更新します。
- `/scan`トピックはQoSに互換性のないReliabilityが設定されていたため、RViz側を`Best Effort`に変更します
- `/graph_visualiztion`トピックは、トピックのネームスペースが変更されていたため、`/slam_toolbox/graph_visualization`に変更します
ROS 2 FoxyではRVizのパラメータが増えたため（特にトピックのQoS）、`dashing-devel`との互換性はありません。
いいえ
ROS 2 Foxy環境でSLAMサンプルが動作し、RViz上にトピックが表示されることを確認しました。

Update rviz config to visualize scan and graph topics

---

.github/workflows/industrial_ci.yml

#27 でFoxyのみに対応した変更が取り入れられます。
masterブランチでのCIチェックをパスするために、CIのチェック項目からROS Dashingを取り除きます。
この変更は`master`および`foxy-devel`ブランチのみに適用されます。

Remove dashing check from CI

---

launch/direction_controller.launch.py
launch/line_follower.launch.py
launch/mouse_with_lidar.launch.py
launch/object_tracking.launch.py
launch/slam.launch.py
launch/teleop_joy.launch.py

Foxyからlaunch_rosでのNodeの記述が変更されます。（[参考情報](https://docs.ros.org/en/foxy/Releases/Release-Foxy-Fitzroy.html#node-name-and-namespace-parameters-changed)  
本PRはその変更に対応します。
ROS 2 Foxyにて、すべてのlaunchファイルを実行し、警告が表示されないことを確認しました。
この変更は`dashing-devel`と互換性がありません。

Remove node_ prefix from launch files

---

README.en.md
README.md

Update README for foxy-devel

---

README.en.md
README.md

地図を保存するコマンドが更新されていたので、READMEに書かれているコマンドも更新しました。
#37 
使用した機材はこちら。ロボットもPCもUbuntu 20.04とROS 2 Foxyを使用しています。
- Raspberry Pi Mouse V3
- Raspberry Pi 4 Model B
SLAMを実行後、以下のコマンドを実行して地図を保存
```sh
ros2 run nav2_map_server map_saver_cli -f ~/maps/mymap
```

Update map command

---

CHANGELOG.rst

Foxy版のパッケージをリリースするため、CHANGELOG.rstを追加しました
いいえ
リリース準備作業のため動作テスト不要です。
いいえ

Prepare foxy release 1.0.0

---

CHANGELOG.rst
README.en.md
README.md
config/joy_dualshock4.yml
package.xml

リリースに向けてmasterの変更をfoxy-develへマージします。
CHANGELOGとpackage.xmlの更新はmasterブランチで実施済みです。

Sync changes from master into foxy-devel

---

CHANGELOG.rst
package.xml

このパッケージをHumble向けにリリースするためにCHANGE.rstとpackage.xmlを更新します。
しません。
テストは行っていません。

HumbleリリースのためにCHANGELOG.rstとpackage.xmlを更新

---

README.en.md
README.md

README（日本語と英語の両方）にGazeboでも実行できることを追記します。
しません。
ドキュメントの変更のみなのでテストは行っていません。

READMEにGazeboでも実行できることを追記

---

CHANGELOG.rst
package.xml

リリースのためにCHANGELOG.rstとpackage.xmlを更新します。
しません。
テストは行っていません。

リリースのためにCHANGELOG.rstとpackage.xmlを更新

---

CHANGELOG.rst
CMakeLists.txt
README.en.md
README.md
include/raspimouse_ros2_examples/object_tracking_component.hpp
launch/object_tracking.launch.py
package.xml
src/object_tracking_component.cpp

2.1.0リリースのためにmasterの変更差分をhumble-develブランチにマージします。
しません。
テストは行っていません。

2.1.0リリースのためにmasterの変更差分をhumble-develへマージ

---

package.xml

#47 で追加したusb_camノードを使用するため、依存関係を更新します。
いいえ
CIでエラーが出ないことのみ確認します。

Add usb_cam dependency

---

CMakeLists.txt
include/raspimouse_ros2_examples/camera_line_follower_component.hpp
launch/camera_line_follower.launch.py
src/camera_line_follower_component.cpp

パスカルケースに統一するため、Camera_Followerクラスの名前をCameraFollowerに変更します。
しません。
シミュレータ環境で動作確認しました。
なし。

Camera_FollowerクラスをCameraFollowerに変更

---

CHANGELOG.rst
package.xml

2.2.0リリースのためにCHANGELOG.rstとpackage.xmlを更新します。
しません。
テストは行っていません。
下記のレビューをお願いいたします。
- CHANGELOG.rst: 2.2.0の更新内容に問題がないか
- package.xml: バージョンが正しいか

2.2.0リリースのためにCHANGELOG.rstとpackage.xmlを更新

---

CHANGELOG.rst
package.xml

2.2.1リリースのためにCHANGELOG.rstとpackage.xmlを更新します。
しません。
テストは行っていません。
なし。

2.2.1リリースのためにCHANGELOG.rstとpackage.xmlを更新

---

CHANGELOG.rst
launch/teleop_joy.launch.py
package.xml
raspimouse_ros2_examples/joystick_control.py

2.2.1リリースのためにmasterの更新内容をhumble-develへマージします。
しません。
テストは行っていません。
なし。

2.2.1リリースのためにmasterの更新内容をhumble-develへマージ

---

CHANGELOG.rst
package.xml

バージョン3.0.0リリースのために、情報をアップデートします。
しません
テストはありません

リリース3.0.0への対応
